version: '3'
services:
  docker-monitor:
    container_name: monitor001
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9444:9444"
    volumes:
      - /var/log:/var/log