version: '3'
services:
  docker-monitor:
    container_name: monitor001
    build: 
      context: ./monitor
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    
  docker-server:
    container_name: server001
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: python server.py
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9444:9444"
    volumes:
      - /var/log:/var/log
